package lima

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/olamide226/avar/internal/deps"
	"github.com/olamide226/avar/internal/provider"
	"github.com/olamide226/avar/internal/types"
)

// nativeSelector is an environment that runs without emulation wherever the
// tests happen to run, so that a test about provisioning is not also a test
// about the machine running it.
func nativeSelector() types.EnvironmentSelector {
	return types.EnvironmentSelector{Distro: types.DistroUbuntu, Version: "24.04", Arch: types.HostArch()}
}

// foreignSelector is an environment that must be emulated wherever the tests
// run (REQ-4.6).
func foreignSelector() types.EnvironmentSelector {
	arch := types.ArchAMD64
	if types.HostArch() == types.ArchAMD64 {
		arch = types.ArchARM64
	}
	return types.EnvironmentSelector{Distro: types.DistroUbuntu, Version: "24.04", Arch: arch}
}

const testMachine = "avr-ubuntu-24.04-arm64"

// ownedRecord is avar's record of the machine under test, which is the second
// half of what ownership means (REQ-5.4, PROP-6).
func ownedRecord(name string) types.MachineRecord {
	return types.MachineRecord{Name: name, Provider: types.ProviderLima, Selector: nativeSelector(), Kind: types.KindShared}
}

// shares builds the mount set Lima would be given for these project
// directories: the identity mapping, writable, which is what MapProjectPath
// produces on this backend (REQ-6.1).
func shares(dirs ...string) []types.MountSpec {
	out := make([]types.MountSpec, 0, len(dirs))
	for _, dir := range dirs {
		out = append(out, types.MountSpec{HostPath: dir, GuestPath: dir, Writable: true})
	}
	return out
}

func assertArgvs(t *testing.T, got, want []string) {
	t.Helper()
	if !reflect.DeepEqual(got, want) {
		t.Errorf("limactl was driven differently than expected.\nwant: %v\ngot:  %v", want, got)
	}
}

func TestNew_RequiresItsCollaborators(t *testing.T) {
	cases := map[string]Options{
		"no limactl path": {Runner: newFakeRunner(), LogsDir: t.TempDir()},
		"no runner":       {Lima: deps.Lima{Path: "/usr/local/bin/limactl"}, LogsDir: t.TempDir()},
		"no log dir":      {Lima: deps.Lima{Path: "/usr/local/bin/limactl"}, Runner: newFakeRunner()},
	}
	for name, opts := range cases {
		t.Run(name, func(t *testing.T) {
			if _, err := New(opts); err == nil {
				t.Fatal("a Provider was built without a collaborator it cannot work without")
			}
		})
	}
}

func TestEnsureMachine_ColdCreate_REQ_1_2(t *testing.T) {
	project := t.TempDir()
	runner := newFakeRunner().listing(fixture(t, "list-empty.json"))
	runner.streamOutput = "INFO[0000] Attempting to download the image\nINFO[0042] READY. Run `limactl shell` to open the shell.\n"
	p := newTestProvider(t, runner, newFakeRecords())
	sink := &recordingSink{}

	spec := provider.MachineSpec{
		Name:     testMachine,
		Selector: nativeSelector(),
		Kind:     types.KindShared,
		Mounts:   shares(project),
	}
	if err := p.EnsureMachine(context.Background(), spec, sink); err != nil {
		t.Fatalf("EnsureMachine: %v", err)
	}

	assertArgvs(t, runner.limactlArgvs(), []string{
		"limactl list --json",
		"limactl start --name " + testMachine + " --tty=false " + configPathPlaceholder,
		"limactl shell --workdir / " + testMachine + " -- test -d " + project,
		"limactl shell --workdir / " + testMachine + " -- test -w " + project,
	})

	// The configuration limactl was pointed at is the generated one, not a
	// Lima stock template.
	if !strings.Contains(runner.configWritten, "Generated by avar") {
		t.Errorf("limactl was not given avar's generated configuration:\n%s", runner.configWritten)
	}
	if !strings.Contains(runner.configWritten, `location: "`+project+`"`) {
		t.Errorf("the project directory did not reach the generated configuration:\n%s", runner.configWritten)
	}

	creating := sink.of(types.ProgressCreating)
	if len(creating) != 1 {
		t.Fatalf("want one Creating event, got %d: %v", len(creating), sink.kinds())
	}
	// REQ-1.2 asks for a human-readable line naming the environment and its
	// size, e.g. "Ubuntu 24.04 · arm64 · 4 CPU · 8 GB RAM".
	for _, want := range []string{"Ubuntu 24.04", "CPU", "GB RAM"} {
		if !strings.Contains(creating[0].Message, want) {
			t.Errorf("the Creating message does not mention %q: %q", want, creating[0].Message)
		}
	}
}

func TestEnsureMachine_WritesTheProvisioningLog_REQ_1_6(t *testing.T) {
	runner := newFakeRunner().listing(fixture(t, "list-empty.json"))
	runner.streamOutput = "INFO[0000] Attempting to download the image\n"
	p := newTestProvider(t, runner, newFakeRecords())

	err := p.EnsureMachine(context.Background(), provider.MachineSpec{
		Name: testMachine, Selector: nativeSelector(),
	}, types.DiscardProgress)
	if err != nil {
		t.Fatalf("EnsureMachine: %v", err)
	}

	log, readErr := os.ReadFile(filepath.Join(p.logsDir, testMachine+"-create.log"))
	if readErr != nil {
		t.Fatalf("reading the provisioning log: %v", readErr)
	}
	if !strings.Contains(string(log), "Attempting to download the image") {
		t.Errorf("provisioning output did not reach the log: %q", log)
	}
}

func TestEnsureMachine_ForwardsProvisioningOutputAsProgress(t *testing.T) {
	runner := newFakeRunner().listing(fixture(t, "list-empty.json"))
	runner.streamOutput = "INFO[0000] Attempting to download the image\n\nINFO[0042] READY.\n"
	p := newTestProvider(t, runner, newFakeRecords())
	sink := &recordingSink{}

	if err := p.EnsureMachine(context.Background(), provider.MachineSpec{
		Name: testMachine, Selector: nativeSelector(),
	}, sink); err != nil {
		t.Fatalf("EnsureMachine: %v", err)
	}

	logs := sink.of(types.ProgressLog)
	if len(logs) != 2 {
		t.Fatalf("want the two non-empty output lines forwarded, got %d: %v", len(logs), logs)
	}
	if logs[0].Message != "INFO[0000] Attempting to download the image" {
		t.Errorf("forwarded line = %q", logs[0].Message)
	}
}

func TestEnsureMachine_WarmPathMakesNoExtraCalls_REQ_17_1(t *testing.T) {
	// The machine in the fixture is Running. This is what happens on every
	// single avr invocation once an environment exists, and the whole latency
	// budget for it is ~500 ms — so it must cost exactly one question to Lima
	// and change nothing.
	runner := newFakeRunner().listing(fixture(t, "list-mixed.json"))
	p := newTestProvider(t, runner, newFakeRecords(ownedRecord("avr-ubuntu-24.04-arm64")))
	sink := &recordingSink{}

	err := p.EnsureMachine(context.Background(), provider.MachineSpec{
		Name:     "avr-ubuntu-24.04-arm64",
		Selector: nativeSelector(),
		// A different mount set than the machine has. EnsureMachine must still
		// not reconfigure: registering a project is SetMounts' job, and doing
		// it here would restart the machine on an ordinary warm invocation.
		Mounts: shares("/Users/dev/code/somewhere-else"),
	}, sink)
	if err != nil {
		t.Fatalf("EnsureMachine: %v", err)
	}

	assertArgvs(t, runner.limactlArgvs(), []string{"limactl list --json"})
	if len(sink.kinds()) != 0 {
		t.Errorf("the warm path emitted progress, which the user would see on every command: %v", sink.kinds())
	}
}

func TestEnsureMachine_StartsAStoppedMachine_REQ_1_3(t *testing.T) {
	runner := newFakeRunner().listing(fixture(t, "list-mixed.json"))
	p := newTestProvider(t, runner, newFakeRecords(ownedRecord("avr-fedora-42-amd64")))
	sink := &recordingSink{}

	spec := provider.MachineSpec{
		Name:     "avr-fedora-42-amd64",
		Selector: types.EnvironmentSelector{Distro: types.DistroFedora, Version: "42", Arch: types.ArchAMD64},
	}
	if err := p.EnsureMachine(context.Background(), spec, sink); err != nil {
		t.Fatalf("EnsureMachine: %v", err)
	}

	assertArgvs(t, runner.limactlArgvs(), []string{
		"limactl list --json",
		"limactl start --tty=false avr-fedora-42-amd64",
	})
	if kinds := sink.kinds(); len(kinds) != 1 || kinds[0] != types.ProgressStarting {
		t.Errorf("want a single Starting event, got %v", kinds)
	}
}

func TestEnsureMachine_WarnsOnceAboutEmulation_REQ_4_6(t *testing.T) {
	runner := newFakeRunner().listing(fixture(t, "list-empty.json"))
	p := newTestProvider(t, runner, newFakeRecords())
	sink := &recordingSink{}

	err := p.EnsureMachine(context.Background(), provider.MachineSpec{
		Name: "avr-ubuntu-24.04-foreign", Selector: foreignSelector(),
	}, sink)
	if err != nil {
		t.Fatalf("EnsureMachine: %v", err)
	}

	warnings := sink.of(types.ProgressWarning)
	if len(warnings) != 1 {
		t.Fatalf("want exactly one emulation warning at provision time, got %d: %v", len(warnings), sink.kinds())
	}
	if !strings.Contains(warnings[0].Message, "emulation") {
		t.Errorf("the warning does not explain the cost of emulation: %q", warnings[0].Message)
	}
	// The warning belongs before the slow part starts, not after it.
	kinds := sink.kinds()
	if len(kinds) < 2 || kinds[0] != types.ProgressCreating || kinds[1] != types.ProgressWarning {
		t.Errorf("want Creating then Warning before provisioning, got %v", kinds)
	}
}

func TestEnsureMachine_NativeArchIsNotWarnedAbout_REQ_4_6(t *testing.T) {
	runner := newFakeRunner().listing(fixture(t, "list-empty.json"))
	p := newTestProvider(t, runner, newFakeRecords())
	sink := &recordingSink{}

	if err := p.EnsureMachine(context.Background(), provider.MachineSpec{
		Name: testMachine, Selector: nativeSelector(),
	}, sink); err != nil {
		t.Fatalf("EnsureMachine: %v", err)
	}
	if warnings := sink.of(types.ProgressWarning); len(warnings) != 0 {
		t.Errorf("a native environment was warned about: %v", warnings)
	}
}

func TestEnsureMachine_FailedCreateDeletesThePartialMachine_PROP_7(t *testing.T) {
	provisionFailed := errors.New("exit status 1: failed to download the image")
	runner := newFakeRunner().listing(fixture(t, "list-empty.json")).failOn("start", provisionFailed)
	runner.streamOutput = "ERRO[0007] failed to download the image\n"
	p := newTestProvider(t, runner, newFakeRecords())

	err := p.EnsureMachine(context.Background(), provider.MachineSpec{
		Name: testMachine, Selector: nativeSelector(),
	}, types.DiscardProgress)
	if err == nil {
		t.Fatal("a failed provision was reported as success")
	}

	assertArgvs(t, runner.limactlArgvs(), []string{
		"limactl list --json",
		"limactl start --name " + testMachine + " --tty=false " + configPathPlaceholder,
		"limactl delete --force " + testMachine,
	})
	if !errors.Is(err, provisionFailed) {
		t.Errorf("the underlying cause was not wrapped: %v", err)
	}
	// The error has to name the log, because the tail of it is what says why
	// (design §6).
	wantLog := filepath.Join(p.logsDir, testMachine+"-create.log")
	if !strings.Contains(err.Error(), wantLog) {
		t.Errorf("the error does not name the provisioning log %s: %v", wantLog, err)
	}
	if !strings.Contains(err.Error(), "has been removed") {
		t.Errorf("the error does not say the partial machine was cleaned up: %v", err)
	}
}

func TestEnsureMachine_CancellationCleansUpAndWrapsContextError_PROP_7(t *testing.T) {
	// Ctrl-C during provisioning. The cleanup has to happen on a context that
	// is not the cancelled one, or nothing would get cleaned up at all.
	ctx, cancel := context.WithCancel(context.Background())
	runner := newFakeRunner().listing(fixture(t, "list-empty.json"))
	runner.onStream = func(context.Context) error {
		cancel()
		return context.Canceled
	}
	p := newTestProvider(t, runner, newFakeRecords())

	err := p.EnsureMachine(ctx, provider.MachineSpec{
		Name: testMachine, Selector: nativeSelector(),
	}, types.DiscardProgress)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("an interrupted create must report cancellation, got: %v", err)
	}
	assertArgvs(t, runner.limactlArgvs(), []string{
		"limactl list --json",
		"limactl start --name " + testMachine + " --tty=false " + configPathPlaceholder,
		"limactl delete --force " + testMachine,
	})
	if !strings.Contains(err.Error(), "interrupted") {
		t.Errorf("the error reads like a failure rather than an interruption: %v", err)
	}
}

func TestEnsureMachine_UnverifiableMountAbandonsTheCreate_REQ_6_5(t *testing.T) {
	project := t.TempDir()
	runner := newFakeRunner().listing(fixture(t, "list-empty.json")).
		failOn("shell", errors.New("exit status 1"))
	p := newTestProvider(t, runner, newFakeRecords())

	err := p.EnsureMachine(context.Background(), provider.MachineSpec{
		Name: testMachine, Selector: nativeSelector(), Mounts: shares(project),
	}, types.DiscardProgress)
	if err == nil {
		t.Fatal("a machine whose project directory did not appear in the guest was accepted")
	}
	if !strings.Contains(err.Error(), project) {
		t.Errorf("the error does not name the directory that is missing: %v", err)
	}
	if got := runner.limactlArgvs(); got[len(got)-1] != "limactl delete --force "+testMachine {
		t.Errorf("the unusable machine was left behind: %v", got)
	}
}

func TestEnsureMachine_MissingProjectDirectoryFailsBeforeProvisioning_REQ_6_5(t *testing.T) {
	runner := newFakeRunner().listing(fixture(t, "list-empty.json"))
	p := newTestProvider(t, runner, newFakeRecords())

	err := p.EnsureMachine(context.Background(), provider.MachineSpec{
		Name: testMachine, Selector: nativeSelector(),
		Mounts: shares(filepath.Join(t.TempDir(), "gone")),
	}, types.DiscardProgress)
	if err == nil {
		t.Fatal("a directory that does not exist was accepted as a project to share")
	}
	// Nothing was provisioned, so there is nothing to clean up.
	assertArgvs(t, runner.limactlArgvs(), []string{"limactl list --json"})
}

func TestEnsureMachine_BrokenMachineIsReportedNotDestroyed(t *testing.T) {
	// A broken machine may hold work the user has not pushed anywhere. avar
	// reports it; deleting is `avr reset`, which is the user's decision.
	runner := newFakeRunner().listing(fixture(t, "list-mixed.json"))
	p := newTestProvider(t, runner, newFakeRecords(ownedRecord("avr-debian-12-arm64")))

	err := p.EnsureMachine(context.Background(), provider.MachineSpec{
		Name:     "avr-debian-12-arm64",
		Selector: types.EnvironmentSelector{Distro: types.DistroDebian, Version: "12", Arch: types.ArchARM64},
	}, types.DiscardProgress)
	if err == nil {
		t.Fatal("a broken machine was reported as ready")
	}
	assertArgvs(t, runner.limactlArgvs(), []string{"limactl list --json"})
	if !strings.Contains(err.Error(), "avr status") {
		t.Errorf("the error does not say what to do next: %v", err)
	}
}

func TestEnsureMachine_StartFailureDoesNotDestroyTheMachine(t *testing.T) {
	runner := newFakeRunner().listing(fixture(t, "list-mixed.json")).
		failOn("start", errors.New("exit status 1"))
	p := newTestProvider(t, runner, newFakeRecords(ownedRecord("avr-fedora-42-amd64")))

	err := p.EnsureMachine(context.Background(), provider.MachineSpec{
		Name:     "avr-fedora-42-amd64",
		Selector: types.EnvironmentSelector{Distro: types.DistroFedora, Version: "42", Arch: types.ArchAMD64},
	}, types.DiscardProgress)
	if err == nil {
		t.Fatal("a failed start was reported as success")
	}
	for _, argv := range runner.limactlArgvs() {
		if strings.HasPrefix(argv, "limactl delete") {
			t.Fatalf("an existing machine was deleted because it would not start: %v", runner.limactlArgvs())
		}
	}
}

func TestStop_StopsARunningMachine_REQ_5_2(t *testing.T) {
	runner := newFakeRunner().listing(fixture(t, "list-mixed.json"))
	p := newTestProvider(t, runner, newFakeRecords(ownedRecord("avr-ubuntu-24.04-arm64")))
	sink := &recordingSink{}

	if err := p.Stop(context.Background(), "avr-ubuntu-24.04-arm64", sink); err != nil {
		t.Fatalf("Stop: %v", err)
	}
	assertArgvs(t, runner.limactlArgvs(), []string{
		"limactl list --json",
		"limactl stop avr-ubuntu-24.04-arm64",
	})
	if kinds := sink.kinds(); len(kinds) != 1 || kinds[0] != types.ProgressStopping {
		t.Errorf("want a single Stopping event, got %v", kinds)
	}
}

func TestStop_AlreadyStoppedIsASilentNoOp(t *testing.T) {
	runner := newFakeRunner().listing(fixture(t, "list-mixed.json"))
	p := newTestProvider(t, runner, newFakeRecords(ownedRecord("avr-fedora-42-amd64")))
	sink := &recordingSink{}

	if err := p.Stop(context.Background(), "avr-fedora-42-amd64", sink); err != nil {
		t.Fatalf("Stop: %v", err)
	}
	assertArgvs(t, runner.limactlArgvs(), []string{"limactl list --json"})
	if kinds := sink.kinds(); len(kinds) != 0 {
		t.Errorf("stopping an already stopped machine said something: %v", kinds)
	}
}

func TestStop_UnknownMachineIsNotFound(t *testing.T) {
	runner := newFakeRunner().listing(fixture(t, "list-empty.json"))
	p := newTestProvider(t, runner, newFakeRecords(ownedRecord(testMachine)))

	err := p.Stop(context.Background(), testMachine, types.DiscardProgress)
	if !errors.Is(err, provider.ErrMachineNotFound) {
		t.Fatalf("want ErrMachineNotFound so the caller can tell an absent environment from a stopped one, got: %v", err)
	}
}

func TestDelete_IsIdempotent_REQ_1_6(t *testing.T) {
	// Delete is how avar cleans up after a crash, where the caller cannot know
	// what survived.
	runner := newFakeRunner().listing(fixture(t, "list-empty.json"))
	p := newTestProvider(t, runner, newFakeRecords())

	if err := p.Delete(context.Background(), testMachine); err != nil {
		t.Fatalf("deleting a machine that does not exist must succeed: %v", err)
	}
	assertArgvs(t, runner.limactlArgvs(), []string{"limactl list --json"})
}

func TestDelete_RemovesTheMachine(t *testing.T) {
	runner := newFakeRunner().listing(fixture(t, "list-mixed.json"))
	p := newTestProvider(t, runner, newFakeRecords(ownedRecord("avr-ubuntu-24.04-arm64")))

	if err := p.Delete(context.Background(), "avr-ubuntu-24.04-arm64"); err != nil {
		t.Fatalf("Delete: %v", err)
	}
	assertArgvs(t, runner.limactlArgvs(), []string{
		"limactl list --json",
		"limactl delete --force avr-ubuntu-24.04-arm64",
	})
}

func TestDelete_WorksWithoutARecord_PROP_7(t *testing.T) {
	// A machine that was created but never recorded is exactly the state a
	// crash between the two leaves behind. Requiring a record here would make
	// it impossible to clean up.
	runner := newFakeRunner().listing(fixture(t, "list-mixed.json"))
	p := newTestProvider(t, runner, newFakeRecords())

	if err := p.Delete(context.Background(), "avr-ubuntu-24.04-arm64"); err != nil {
		t.Fatalf("Delete: %v", err)
	}
	if got := runner.limactlArgvs(); got[len(got)-1] != "limactl delete --force avr-ubuntu-24.04-arm64" {
		t.Errorf("an unrecorded avar machine could not be cleaned up: %v", got)
	}
}

func TestEveryMachineOperation_RefusesAMachineAvarDoesNotOwn_PROP_6(t *testing.T) {
	// Both halves of ownership: a name that is not avar's at all, and a name
	// that looks like avar's but which avar has no record of. Neither may
	// produce a single subprocess.
	foreign := []string{"default", "colima", "avr-ubuntu-24.04-arm64"}
	records := newFakeRecords() // avar owns nothing

	operations := map[string]func(*Provider, string) error{
		"EnsureMachine": func(p *Provider, name string) error {
			return p.EnsureMachine(context.Background(), provider.MachineSpec{Name: name, Selector: nativeSelector()}, types.DiscardProgress)
		},
		"AppliedMounts": func(p *Provider, name string) error {
			_, err := p.AppliedMounts(context.Background(), name)
			return err
		},
		"SetMounts": func(p *Provider, name string) error {
			return p.SetMounts(context.Background(), name, nil, types.DiscardProgress)
		},
		"Stop": func(p *Provider, name string) error {
			return p.Stop(context.Background(), name, types.DiscardProgress)
		},
		"Delete": func(p *Provider, name string) error {
			return p.Delete(context.Background(), name)
		},
	}

	for op, call := range operations {
		for _, name := range foreign {
			// EnsureMachine and Delete legitimately run before or after a
			// machine has a record, so for them ownership is the name alone.
			nameIsAvars := strings.HasPrefix(name, types.MachineNamePrefix)
			if nameIsAvars && (op == "EnsureMachine" || op == "Delete") {
				continue
			}
			t.Run(op+"/"+name, func(t *testing.T) {
				runner := newFakeRunner().listing(fixture(t, "list-foreign-only.json"))
				p := newTestProvider(t, runner, records)

				err := call(p, name)
				if !errors.Is(err, provider.ErrNotOwned) {
					t.Fatalf("%s(%q) = %v, want an error wrapping ErrNotOwned", op, name, err)
				}
				if calls := runner.calls(); len(calls) != 0 {
					t.Errorf("%s(%q) had side effects before refusing: %v", op, name, runner.argvs())
				}
			})
		}
	}
}

func TestShell_IsTask8sWork(t *testing.T) {
	// The placeholder exists only because Provider is one interface. Task 8
	// replaces this file wholesale.
	p := newTestProvider(t, newFakeRunner(), newFakeRecords())
	if _, err := p.Shell(context.Background(), testMachine, provider.ShellOpts{}); err == nil {
		t.Fatal("the Shell placeholder reported success")
	}
}

func TestHostResources_ProbesTheHostWhenNotPinned(t *testing.T) {
	runner := newFakeRunner()
	runner.memsize = "34359738368" // 32 GiB
	p, err := New(Options{
		Lima:    deps.Lima{Path: "/opt/homebrew/bin/limactl"},
		Runner:  runner,
		LogsDir: t.TempDir(),
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	host := p.hostResources(context.Background())
	if host.MemoryGB != 32 {
		t.Errorf("host memory = %v GiB, want 32", host.MemoryGB)
	}
	if host.CPUs <= 0 {
		t.Errorf("host CPUs = %d, want the machine's core count", host.CPUs)
	}
}

func TestHostResources_FallsBackWhenTheProbeFails(t *testing.T) {
	runner := newFakeRunner()
	runner.sysctlErr = errors.New("sysctl: unknown oid 'hw.memsize'")
	p, err := New(Options{
		Lima:    deps.Lima{Path: "/opt/homebrew/bin/limactl"},
		Runner:  runner,
		LogsDir: t.TempDir(),
	})
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	// Under-provisioning is recoverable; over-provisioning on a small host is
	// what REQ-17.4 exists to prevent.
	if host := p.hostResources(context.Background()); host.MemoryGB != fallbackHostMemoryGB {
		t.Errorf("host memory = %v GiB, want the conservative fallback %v", host.MemoryGB, fallbackHostMemoryGB)
	}
}
